import { GameDefinition } from './types';

export const gamesList: GameDefinition[] = [
  {
    id: 'super-ace',
    title: 'Super Ace',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/super_ace_game_1780269991180.png',
  },
  {
    id: 'boxing-king',
    title: 'Boxing King',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/boxing_king_game_1780270009867.png',
  },
  {
    id: 'golden-empire',
    title: 'Golden Empire',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/golden_empire_game_1780270026882.png',
  },
  {
    id: 'crazy-777',
    title: 'Crazy 777',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/crazy_777_game_1780270043424.png',
  },
  {
    id: 'ali-baba',
    title: 'Ali Baba',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/ali_baba_game_1780270060780.png',
  },
  {
    id: 'mega-ace',
    title: 'Mega Ace',
    category: 'slot',
    provider: 'Mega Ace',
    imageUrl: '/images/mega_ace_game_1780270132158.png',
  },
  {
    id: 'charge-buffalo',
    title: 'Charge Buffalo',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/charge_buffalo_game_1780270078919.png',
  },
  {
    id: 'jackpot-joker',
    title: 'Jackpot Joker',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/jackpot_joker_game_1780270093866.png',
  },
  {
    id: 'legacy-of-egypt',
    title: 'Legacy of Egypt',
    category: 'slot',
    provider: 'Legacy of Egypt',
    imageUrl: '/images/legacy_of_egypt_game_1780270152238.png',
  },
  {
    id: 'fortune-gems3',
    title: 'Fortune Gems 3',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/fortune_gems3_game_1780270173533.png',
  },
  {
    id: 'money-coming',
    title: 'Money Coming',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/money_coming_game_1780270190013.png',
  },
  {
    id: 'magic-ace',
    title: 'Magic Ace',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/magic_ace_game_1780270207847.png',
  },
  {
    id: 'jili-caishen',
    title: 'Jili Caishen',
    category: 'slot',
    provider: 'JILI',
    imageUrl: '/images/jili_caishen_game_1780270226779.png',
  },
  {
    id: 'dinosaur-tycoon-ii',
    title: 'Dinosaur Tycoon II',
    category: 'fish',
    provider: 'JILI',
    imageUrl: '/images/dinosaur_tycoon_ii_game_1780270243299.png',
  },
  {
    id: 'cricket-king-18',
    title: 'Cricket King 18',
    category: 'hot',
    provider: 'JILI',
    imageUrl: '/images/cricket_king_18_game_1780270260403.png',
  },
  {
    id: 'happy-fishing',
    title: 'Happy Fishing',
    category: 'fish',
    provider: 'JILI',
    imageUrl: '/images/happy_fishing_game_1780270288970.png',
  },
  {
    id: 'mega-fishing',
    title: 'Mega Fishing',
    category: 'fish',
    provider: 'JILI',
    imageUrl: '/images/mega_fishing_game_1780270112571.png',
  },
];
